// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG-ciwZoUPlaTAsjtGTuFjj_iqrF9pN5M',
    appId: '1:537573796276:web:032b2e3bf10244e0332ae1',
    messagingSenderId: '537573796276',
    projectId: 'garbagetrucknotifier',
    authDomain: 'garbagetrucknotifier.firebaseapp.com',
    storageBucket: 'garbagetrucknotifier.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qqZF-IR3ymp0x4P23ygdubsKuWuIqp4',
    appId: '1:537573796276:android:dc1cdf1f4e879af3332ae1',
    messagingSenderId: '537573796276',
    projectId: 'garbagetrucknotifier',
    storageBucket: 'garbagetrucknotifier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMIuuxHcy3V2XdmasM6b2wZlHCLDp7bVg',
    appId: '1:537573796276:ios:377d68002a009372332ae1',
    messagingSenderId: '537573796276',
    projectId: 'garbagetrucknotifier',
    storageBucket: 'garbagetrucknotifier.firebasestorage.app',
    iosBundleId: 'com.example.userReg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMIuuxHcy3V2XdmasM6b2wZlHCLDp7bVg',
    appId: '1:537573796276:ios:377d68002a009372332ae1',
    messagingSenderId: '537573796276',
    projectId: 'garbagetrucknotifier',
    storageBucket: 'garbagetrucknotifier.firebasestorage.app',
    iosBundleId: 'com.example.userReg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG-ciwZoUPlaTAsjtGTuFjj_iqrF9pN5M',
    appId: '1:537573796276:web:91a2b9500575faa1332ae1',
    messagingSenderId: '537573796276',
    projectId: 'garbagetrucknotifier',
    authDomain: 'garbagetrucknotifier.firebaseapp.com',
    storageBucket: 'garbagetrucknotifier.firebasestorage.app',
  );
}
